#-------------------------------
# General Site Settings

title: ZeoSpec | Arun Teja Godavarthi
description: Personal blog of ZeoSpec ( Arun Teja Godavarthi ). # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zeospec.com" # the base hostname & protocol for your site, e.g. http://example.com
og_img: zeospec.jpg

#-------------------------------
# About Section
author-name: ZeoSpec
author-avatar: zeospec.jpg

#-------------------------------
# Contact links
facebook:  https://facebook.com/zeospec # Add your Facebook handle
twitter:   https://twitter.com/zeospec # Add your Facebook handle
instagram: https://www.instagram.com/zeospec # Add your Facebook handle
mail:  mailto:me@zeospec.com # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: '/:year-:month-:day-:title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

paginate: 7
paginate_path: "/page:num"

# Archives
# jekyll-archives:
#   enabled: all
#   layout: archive
#   permalinks:
#     category: '/:name/'
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/clubs/:name/'
    

include:
  - _pages
  - _redirects

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/